### ISSUE TITLE
Where to get query nouns?

### ISSUE THREAD

**Issue by Mikolasek93** [Rhymen/go-whatsapp#68] opened 2018-10-22 05:16 UTC
Hello, 
I'm trying to add some features to your existing solution (delete chat for now), I have only one question.
Where do you get all these nouns used in writebinary, query. 
I mean like "exist", "remove", "status" etc.

Thanks a lot!

**Comment by SchulteMK** [comment] 2018-11-13 07:45
Basically you have to debug the whatsapp-web javascript file. Search for the send method of the websocket and set a breakpoint there. The execution will hold on every message/request send to the servers. You should be able to see a debugObject which holds all protobuf definitions and all pramameters used for sending.

**Comment by Rhymen** [comment] 2019-02-03 14:49
Duplicate of #67

**Closed by Rhymen** 2019-02-03 14:49 UTC
