### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by AbyssEkko** [Rhymen/go-whatsapp#170] opened 2019-06-11 13:24 UTC
> error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}
> 
> login successful, session: {uocSvrqQWvColFnkQ0aW2w==   [] [] }

```
go func() {
		terminal := qrcodeTerminal.New()
		terminal.Get(<-qr).Print()     //err here
	}()



```

I have no session in /tmp, the problem generates when trying to generate QR code. Ive already updated to last version of the repo.
Thanks in advance

**Comment by iileandro** [comment] 2019-06-12 05:14
Same problem here. Anybody knows the cause?

**Comment by hrizal** [comment] 2019-06-12 05:56
> error logging in: error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}

Yups

**Comment by zeftcool** [comment] 2019-06-12 06:05
i found same problem.
fixed by change 
longClientName and shortClientName with the short string

**Comment by reznikartem** [comment] 2019-06-12 07:51
> i found same problem.
> fixed by change
> longClientName and shortClientName with the short string

Hello. Can you provide working code example?

**Comment by reznikartem** [comment] 2019-06-12 08:12
We receive error error on login:
 decoding login connResp: json: cannot unmarshal array into Go value of type map[string]interface {} 
Json is: ["Cmd",{"type":"update"}]

I suppose, that problem not in longClientName and shortClientName :(

@Rhymen, we are waiting for you! :)

**Comment by it-sumanp** [comment] 2019-06-12 09:18
**_session.go_** file line number **152**.
changing {0, 3, 225} to {0,3,3324} did solved it.

**Comment by it-sumanp** [comment] 2019-06-12 09:19
I got this value from chrome but I did not understand the actual issue here, can anybody help ?

**Comment by tulir** [comment] 2019-06-12 09:28
The problem seems to be that whatsapp is disconnecting users with old whatsapp protocol versions. go-whatsapp probably just needs to update the protobuf schema and that number in session.go (and also keep updating those every time they change)

**Comment by reznikartem** [comment] 2019-06-12 09:34
> **_session.go_** file line number **152**.
> changing {0, 3, 225} to {0,3,3324} did solved it.

Thank you, it`s solved our problem!

**Comment by tulir** [comment] 2019-06-12 09:36
Note that the version number is in two places: https://github.com/Rhymen/go-whatsapp/blob/master/session.go#L152 and https://github.com/Rhymen/go-whatsapp/blob/master/session.go#L306

Restoring sessions might not work if you don't change the one on line 306 too.

**Comment by Romerito007** [comment] 2019-06-12 13:48
@tulir I checked on your fork that you updated protobuf. Right?

**Comment by tulir** [comment] 2019-06-12 13:51
Yes, although it looks like there's another protobuf update since then (version 3324, it was at 2846 when I updated).

**Comment by emauro** [comment] 2019-06-12 13:52
Using the last commit solves the problem.

**Comment by Romerito007** [comment] 2019-06-12 14:07
Thank you!

**Comment by franklinsales** [comment] 2019-06-12 17:50
How @it-sumanp told:
> session.go file line number 152.
> changing {0, 3, 225} to {0,3,3324} did solved it.

And how @tulir told it's necessary update in the same file(session.go) at line 306 too.

Thx it's worked to me.

**Comment by leoteixeira2016** [comment] 2019-06-12 18:53
work?

**Comment by AbyssEkko** [comment] 2019-06-12 19:09
What made it for me was to change server, i just copied all my files into a backup server i have and started working. Dont know why though

**Comment by houstondapaz** [comment] 2019-06-13 23:36
I thinks this issue was resolved with the last commits @SchulteMK

**Closed** 2019-06-14 01:59 UTC

**Comment by AbyssEkko** [comment] 2019-06-14 13:07
What was happening is I was updating the wrong folder, after i went to /go/src/github.com/Rhymen/go-whatsapp un updated de git it worked just fine in the other server.
