### ISSUE TITLE
panic: repeated read on failed websocket connection

### ISSUE THREAD

**Issue by aight8** [Rhymen/go-whatsapp#88] opened 2019-02-04 13:49 UTC
After running the client for a while, after some hours I very often get a websocket related panic error.
Wouldn't be it nicer if the library would catch this and notify the lib user with a channel message?

```
error writing to socket: write tcp 10.10.1.225:61323->169.60.79.23:443: write: broken pipe
panic: repeated read on failed websocket connection

goroutine 41 [running]:
github.com/gorilla/websocket.(*Conn).NextReader(0xc0000a0160, 0x50b35e0, 0xc003961312, 0x2, 0xc0039619c0, 0xc000466600)
	/Users/xxx/go/src/github.com/gorilla/websocket/conn.go:968 +0x356
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc0000a0160, 0xc003a09b60, 0xc0031eaf60, 0x1, 0x1, 0x4b2b600, 0xc003a09b60)
	/Users/xxx/go/src/github.com/gorilla/websocket/conn.go:1029 +0x2f
github.com/rhymen/go-whatsapp.(*Conn).readPump(0xc0000a5450)
	/Users/xxx/go/src/github.com/rhymen/go-whatsapp/conn.go:272 +0x73
created by github.com/rhymen/go-whatsapp.NewConn
	/Users/xxx/go/src/github.com/rhymen/go-whatsapp/conn.go:129 +0x1ff
exit status 2
```

**Comment by SchulteMK** [comment] 2019-02-04 19:24
Can you please insert this line `fmt.Printf("Type: %T, Message: %v", err, err)` after line 273 in the conn.go file for debugging purposes and post the output here again?

Did you implement the `HandleError` function in your `Handler`? Does the error get printed multiple times? I took a quick look at the gorilla/websocket code and the panic only gets invoked after 1000+ errors.

**Comment by aight8** [comment] 2019-02-05 09:51
Type: int
Message: []
Error: read tcp 192.168.0.18:52543->169.60.79.83:443: read: operation timed out

Yes, I implemented the HandleError (it get's called correctly in certain situation). But in this case it's not.

Where the error handler get called (example):
```
websocket connection closed(1000, )
INFO[0057] WA disconnected!                              kind=replaced
ERRO[0057] WA error occured                              error="unexpected websocket close: websocket: close 1000 (normal)"
```
line 1=HandleJsonMessage (Cmd object type), line 2=ErrorHandler

**Comment by SchulteMK** [comment] 2019-02-05 17:53
Can you explain me how I can reproduce the issue myself?
I'm not totally sure but I think that we have to maybe redesign the readPump...

**Comment by VinothJ7** [comment] 2019-02-06 10:15
This is because gorilla websocket panics when the number of errors produced by the connection exceeds 1000. This can be solved by re initializing the connection before the error limit of 1000 is reached. Make these changes in readPump() function in conn.go

`func (wac *Conn) readPump() {
	defer wac.wsConn.Close()

	//gorilla websocket causes panic if number of errors is >= 1000
	var error_count = 0

	//reset connection before error count exceeds the websocket limit
	for error_count <= 500 {

		msgType, msg, err := wac.wsConn.ReadMessage()
		if err != nil {
			error_count++
			wac.wsConnOK = false
			if websocket.IsUnexpectedCloseError(err, websocket.CloseGoingAway) {
				wac.handle(fmt.Errorf("unexpected websocket close: %v", err))
			}
			// sleep for a second and retry reading the next message
			time.Sleep(time.Second)
			continue
		}
		wac.wsConnOK = true

		data := strings.SplitN(string(msg), ",", 2)

		//Kepp-Alive Timestmap
		if data[0][0] == '!' {
			msecs, err := strconv.ParseInt(data[0][1:], 10, 64)
			if err != nil {
				fmt.Fprintf(os.Stderr, "Error converting time string to uint: %v\n", err)
				continue
			}
			wac.ServerLastSeen = time.Unix(msecs/1000, (msecs%1000)*int64(time.Millisecond))
			continue
		}

		wac.listenerMutex.RLock()
		listener, hasListener := wac.listener[data[0]]
		wac.listenerMutex.RUnlock()

		if hasListener && len(data[1]) > 0 {
			listener <- data[1]

			wac.listenerMutex.Lock()
			delete(wac.listener, data[0])
			wac.listenerMutex.Unlock()
		} else if msgType == 2 && wac.session != nil && wac.session.EncKey != nil {
			message, err := wac.decryptBinaryMessage([]byte(data[1]))
			if err != nil {
				wac.handle(fmt.Errorf("error decoding binary: %v", err))
				continue
			}

			wac.dispatch(message)
		} else {
			if len(data[1]) > 0 {
				wac.handle(string(data[1]))
			}
		}

	}
}`

**Comment by SchulteMK** [comment] 2019-02-06 11:15
#89

**Comment by SchulteMK** [comment] 2019-02-08 18:35
Can you try out the new version I am working on? It should handle the issue you I think.

If you use go version >1.11 with go.mod support you can just insert this line at the bottom of the go.mod: `replace github.com/Rhymen/go-whatsapp => github.com/SchulteMK/go-whatsapp v0.0.0-20190208183030-823b89523841`

After the error is thrown you can use wac.Restore() to reconnect and relogin.

**Comment by aight8** [comment] 2019-02-12 02:17
@SchulteMK I tested your version, but I get some errors in my app. the WA ErrorHandler receives the following error:

```
received invalid data
github.com/Rhymen/go-whatsapp.init
	/Users/xxx/go/pkg/mod/github.com/!schulte!m!k/go-whatsapp@v0.0.0-20190208183030-823b89523841/errors.go:14
waspy/app/services/whatsappspy.init
	<autogenerated>:1
waspy/app.init
	<autogenerated>:1
main.init
	<autogenerated>:1
runtime.main
	/usr/local/Cellar/go/1.11.5/libexec/src/runtime/proc.go:189
runtime.goexit
	/usr/local/Cellar/go/1.11.5/libexec/src/runtime/asm_amd64.s:1333
error processing data
github.com/Rhymen/go-whatsapp.(*Conn).readPump
	/Users/xxx/go/pkg/mod/github.com/!schulte!m!k/go-whatsapp@v0.0.0-20190208183030-823b89523841/read.go:42
runtime.goexit
	/usr/local/Cellar/go/1.11.5/libexec/src/runtime/asm_amd64.s:1333FATA[0003] WA handle error, cause: error processing data: received invalid data
```

**Comment by slaveofcode** [comment] 2019-02-19 07:19
Any updates on this?

**Comment by SchulteMK** [comment] 2019-02-19 19:21
@aight8 You received an error right? That is the intended behavior of my code. After that error, you can use `wac.Restore()` to establish a connection again.

**Comment by hiwaleakshay** [comment] 2019-02-22 17:00
@SchulteMK Where is your Restore() method? I am not able to find it..

**Comment by x00b** [comment] 2020-04-07 13:48
Hi guys, i got this same problem yesteday... Sorry but i didnt understand the solution. Was the gorilla websocket modification that V3n0me sugested? And, i saw there is a lot of closed issues about this but did the solution was merged by Rhymen master branch?

**Closed** 2020-10-20 21:05 UTC
