### ISSUE TITLE
stop method

### ISSUE THREAD

**Issue by was1l1sk** [Rhymen/go-whatsapp#34] opened 2018-09-12 17:51 UTC
great work
I did not find any method for stopping connection and running gorutins like:
go wac.readPump ()
go wac.writePump ()
go wac.keepAlive (20000, 90000)
I just wrapped the bot in the web interface that the bot activates. And I want to turn it off without closing the whole application. I wanted to close using the context.WithCancel but this is not enough

And... Does whatsapp ban a bots?

**Comment by SchulteMK** [comment] 2018-10-02 09:12
We need to implement a way to stop these goroutines. Maybe check out the fork of @kaxap. He improved on it if I remember correctly.

**Comment by SchulteMK** [comment] 2018-10-02 09:13
@was1l1sk Maybe you can implement the context package into the api and start a PR if you have spare time.

**Comment by kaxap** [comment] 2018-10-02 16:09
@SchulteMK I had the same issue as @was1l1sk so I made this quick hack. The problem is it doesn't close the websocket connection, just signals go routines to stop. The connection is left open, but it is going to be closed by server soon.

**Comment by tulir** [comment] 2019-03-14 15:10
#114 added `Disconnect()`, so I guess this is fixed now?

**Comment by SchulteMK** [comment] 2019-03-14 16:13
Yes you are right. I must have overlooked this issue when I was closing issues related to that PR.

**Closed by SchulteMK** 2019-03-14 16:13 UTC
Labels: enhancement
