### ISSUE TITLE
Getting Message Id

### ISSUE THREAD

**Issue by adrian3ka** [Rhymen/go-whatsapp#71] opened 2018-10-30 04:22 UTC
Can we get message id if send using send() function?

**Comment by highness28** [comment] 2018-10-30 12:28
you can generate your own id it's actually just a random uppercase alpha num 20-30 characters in length

QWERTYUIOP0123456789
QWERTYUIOPASDFGHJKLZ0123456789

You can use those as long as you ensure that the id you are using will not be the same as the one you already sent per person

**Comment by Rhymen** [comment] 2019-02-03 14:52
As we didn't want to block until the message was send and didn't know how to return the id otherwise, we added to option to pass custom ids just as highness described. That should solve your problem so I'm going to close this issue.

**Closed by Rhymen** 2019-02-03 14:52 UTC

**Comment by KrzysztofMadejski** [comment] 2019-02-14 10:54
Duplicate of #43
