### ISSUE TITLE
`error caught in handler: unexpected websocket close: websocket: close 1006 (abnormal closure): unexpected EOF`

### ISSUE THREAD

**Issue by bottookku** [Rhymen/go-whatsapp#106] opened 2019-02-20 01:27 UTC
after 5-6 min each time always after run application. whatsapp all this time running and screen not sleep

**Comment by jasontkh** [comment] 2019-02-20 10:03
i'm facing the same problem.  the error is coming from line 273 in conn.go

is it from whatsapp trying to block us T.T?

**Comment by Vskilet** [comment] 2019-02-20 15:13
Maybe because of a huge amount a message to sync ?

**Comment by hiwaleakshay** [comment] 2019-02-20 15:45
Tried changing IP? Whatsapp number?

**Comment by bottookku** [comment] 2019-02-20 16:04
Yes i try change number whatsapp and golang app stay in my local pc and vps. But i cant might install and lauch emul android on vps  with very good quality internet. But i do it all on one phone and one and one ip. I dont know how control quantity sync trying

**Comment by jasontkh** [comment] 2019-02-21 08:55
it seems that i'm able to fix it by modifying the keep alive interval at line 131, conn.go

`go wac.keepAlive(20000, 90000)` -> `go wac.keepAlive(20000, 60000)`

i guess whatsapp close the connection somewhere around one minute if no communication.
I didn't do something like `go wac.keepAlive(10000, 20000)` as i also don't want to send the keep alive signal too frequent which may lead to a blocking from whatsapp.

**Comment by bottookku** [comment] 2019-02-21 10:20
all to good but i recieve this error
error writing to socket: write tcp 192.168.1.22:49927->157.240.15.53:443: wsasend: An existing connection was forcibly closed by the remote host.

**Comment by bottookku** [comment] 2019-02-22 12:16
but on linux host i also reviece error 1006.

**Comment by hiwaleakshay** [comment] 2019-02-22 16:09
@jasontkh Your solution worked for me, Thanks. I didn't face this issue in my home network, but when deployed on server.

**Comment by bottookku** [comment] 2019-02-22 16:33
@hiwaleakshay how parametrs you add in this function?

**Comment by jasontkh** [comment] 2019-02-22 17:16
I'm not sure about working under Linux env, I'm still developing on my Mac. I guess it is a networking problem rather then OS problem.  Let me get back after I test it on my Linux server.

**Comment by jasontkh** [comment] 2019-02-22 17:20
And I think the code is not trying to reconnect after the network is down.  I am trying to wrap it with another piece if small python code to take care of that.

**Comment by bottookku** [comment] 2019-02-22 17:36
@Jasontkh how parametrs you add in this function? This app correct worked only for high qualty unternet without timeouts ?

**Comment by jasontkh** [comment] 2019-02-22 23:16
I used 20000,60000. I tested only for 10 mins, it looked normal.  

You are right that the application does not handle time out.  I tried to run the application, then unplug the LAN cable ---- nothing happened.  No error even when I send a message.  I guess this is the limitation of the web socket library of golang.

**Comment by bottookku** [comment] 2019-02-23 04:39
when client on timeout, server think what client disconnected and close session.
but client not know what is session has been closed and trying continue session but received error from server.

**Comment by KrzysztofMadejski** [comment] 2019-03-01 13:04
Maybe it should be handled in close handler in the same manner as unexpected close?

https://github.com/Rhymen/go-whatsapp/blob/c9a81e9578840e5c04c49c9e6126a1682faf22fc/conn.go#L167-L179

In that piece of code I'm getting `code = 1000`

**Comment by KrzysztofMadejski** [comment] 2019-03-01 13:19
It may be also handled externally, but then we should expose reconnect by renaming to `Reconnect`

https://github.com/Rhymen/go-whatsapp/blob/c9a81e9578840e5c04c49c9e6126a1682faf22fc/conn.go#L188

And it would be great to create the `Close` function that would be the same as Reconnect's first few lines:

https://github.com/Rhymen/go-whatsapp/blob/c9a81e9578840e5c04c49c9e6126a1682faf22fc/conn.go#L188-L193

**Comment by tulir** [comment] 2019-03-05 14:12
As I mentioned in the previous issue (#98), I'm pretty sure this is caused by c9a81e9578840e5c04c49c9e6126a1682faf22fc. My program would stop working in 3 minutes after startup with that commit, but now that I reverted it, my program has been running fine for over a week.

**Comment by KrzysztofMadejski** [comment] 2019-03-05 14:31
I tested @jasontkh's shorter keepalive and it works. It's true that reconnects each minute is not the best solution.

**Comment by bottookku** [comment] 2019-03-05 15:24
My row 162 wss://web.whatsapp.com/ws is not wss://w3.web.whatsapp.com/ws
But i all the same i recieve 1006

**Comment by bottookku** [comment] 2019-03-05 15:30
Sorry i mistaken i need use old version. I will test it.

**Comment by bottookku** [comment] 2019-03-05 16:00
I think @tulir is right is solved for me

**Comment by bottookku** [comment] 2019-03-06 02:46
error writing to socket: write tcp 192.168.1.22:49194->169.60.79.32:443: wsasend: An existing connection was forcibly closed by the remote host.
panic: repeated read on failed websocket connection

goroutine 9 [running]:
github.com/gorilla/websocket.(*Conn).NextReader(0x12c020c0, 0x9f1660, 0x12d11312, 0x2, 0x12d10060, 0x12c381c0)
        C:/Users/botto/go/src/github.com/gorilla/websocket/conn.go:968 +0x2bc
github.com/gorilla/websocket.(*Conn).ReadMessage(0x12c020c0, 0x0, 0x12caff60, 0x1, 0x1, 0x7b2200, 0x12d10030)
        C:/Users/botto/go/src/github.com/gorilla/websocket/conn.go:1029 +0x25
github.com/Rhymen/go-whatsapp.(*Conn).readPump(0x12c44b40)
        C:/Users/botto/go/src/github.com/Rhymen/go-whatsapp/conn.go:272 +0x5c
created by github.com/Rhymen/go-whatsapp.NewConn

**Comment by bottookku** [comment] 2019-03-06 02:49
it error i recieve if run go on local pc.. wsasend: An existing connection was forcibly closed by the remote host.

but on remote server VPS run go too same recieve 1006..

all it time phone my stay with me with my low quality internet.

**Comment by codenoid** [comment] 2019-03-06 06:10
> go wac.keepAlive(20000, 60000)

it's working !, i already test to disconnect my phone for a while, and reconnect again, and it's fine

and maybe another option is https://github.com/Rhymen/go-whatsapp/issues/88#issuecomment-465273623 , but i haven't use that logic

**Comment by codenoid** [comment] 2019-03-06 06:40
> `go wac.keepAlive(20000, 90000)` -> `go wac.keepAlive(20000, 60000)`

i don't get 1006 error anymore, but my go-whatsapp only app, exit without any printed message

**Comment by SchulteMK** [comment] 2019-03-06 06:59
@codenoid How do you use/run go-whatsapp? Did you implement the `Handler` interface with its method `HandleError`?

**Comment by codenoid** [comment] 2019-03-06 07:17
yes @SchulteMK 

```
//HandleError needs to be implemented to be a valid WhatsApp handler
func (*waHandler) HandleError(err error) {
	fmt.Fprintf(os.Stderr, "error occoured: %v", err)
}
```

**Comment by codenoid** [comment] 2019-03-06 08:21
my bad, sorry it was the `<-time.After(5 * time.Minute)`

**Comment by SchulteMK** [comment] 2019-03-07 20:04
In #114 I reworked the whole connection including the readPump. I decided to close the connection on a connection failure and emit an error through the handler. You can check, if it is an connection failure error and restore the connection with `wac.Restore()`.  I included an example implementation of most of the new features in example/receiveMessages.

**Comment by SchulteMK** [comment] 2019-03-07 20:33
I will test if the connction holds up during the night. If it does I think I can merge the PR

**Comment by codenoid** [comment] 2019-03-07 20:51
yeah, solved with `go wac.keepAlive(20000, 60000)` , otherwise if disconnected, you can use wac.Restore() or restart your application

**Comment by SchulteMK** [comment] 2019-03-09 16:33
#114 is merged. Please reopen the issue again if you encounter the same issue again

**Closed by SchulteMK** 2019-03-09 16:33 UTC

**Comment by imShara** [comment] 2019-06-18 06:46
```
level=error msg="connection to WhatsApp servers failed: websocket: close 1006 (abnormal closure): unexpected EOF" prefix=whatsapp
level=error msg="SendMessage failed: could not send proto: failed to write message: error writing to websocket: write tcp x.x.x.x:x->x.x.x.x:443: write: connection reset by peer" prefix=gateway
```

Using go-whatsapp with matterbridge. Connection fails after a time when mobile application goes offline.
