### ISSUE TITLE
WhatsApp bans clients using old proto version

### ISSUE THREAD

**Issue by berkercanatar** [Rhymen/go-whatsapp#73] opened 2018-11-12 11:28 UTC
I created a new WhatsApp account and when i try to read the qr code, this number got instantly banned. WhatsApp app says your account is banned and i am no longer able to use whatsapp with that number.  I found the js file that contains the proto structure of the new version. Will you update the def.proto file? Or how can i create updated version of def.proto using that js file on WhatsApp web servers?

#48 same problem :/

**Comment by SchulteMK** [comment] 2018-11-13 07:39
I don´t know how the def.proto is created. We got it from [sigalor/whatsapp-web-reveng](https://github.com/sigalor/whatsapp-web-reveng). The latest update there is 3 months old. I already asked for the extraction method over there. [link](https://github.com/sigalor/whatsapp-web-reveng/commit/3a2ec1c5a3ea17c794b2344c9334f47e5684328c)

**Comment by Rhymen** [comment] 2019-02-03 14:58
Duplicate of #48

**Closed by Rhymen** 2019-02-03 14:58 UTC
