### ISSUE TITLE
Error Login in

### ISSUE THREAD

**Issue by mapodesta** [Rhymen/go-whatsapp#345] opened 2020-04-27 12:40 UTC
Hi people , i have problems when i run the example :sendtextmessage/main.go

in cmd :

error logging in: restoring failed: admin login responded with 401

![error](https://user-images.githubusercontent.com/44898573/80373196-139a9f00-886b-11ea-8ef9-132fb22231f8.png)

**Comment by ramacatur** [comment] 2020-04-28 06:30
Check your tmpdir with 

`echo $TMPDIR`

and  remove file `whatsappSession.gob` on tmpdir

run main.go and  rescan qrcode

**Comment by mapodesta** [comment] 2020-04-28 20:06
> Check your tmpdir with
> 
> `echo $TMPDIR`
> 
> and remove file `whatsappSession.gob` on tmpdir
> 
> run main.go and rescan qrcode

Perfect @ramacatur  , i have a question,how i can ask for cmd 'number' and 'text' in console?

sorry for my english

**Comment by ramacatur** [comment] 2020-04-30 03:09
> > Check your tmpdir with
> > `echo $TMPDIR`
> > and remove file `whatsappSession.gob` on tmpdir
> > run main.go and rescan qrcode
> 
> Perfect @ramacatur , i have a question,how i can ask for cmd 'number' and 'text' in console?
> 
> sorry for my english

maybe you can use console ui lib for golang

**Comment by AlmogBaku** [comment] 2020-05-21 22:20
duplicate of #268 ?

**Comment by tguimmaraess** [comment] 2020-05-28 13:28
> Check your tmpdir with
> 
> `echo $TMPDIR`
> 
> and remove file `whatsappSession.gob` on tmpdir
> 
> run main.go and rescan qrcode

My Qr does not appear, What should I do? I get this error: https://github.com/Rhymen/go-whatsapp/issues/376

**Closed** 2020-10-20 20:50 UTC
