### ISSUE TITLE
Hi, issue with get contacts

### ISSUE THREAD

**Issue by nuwaida** [Rhymen/go-whatsapp#21] opened 2018-08-11 10:45 UTC
I also used the function of Contacts(), and it  looks like when you tries to populate the store with contacts, the code panics with the following stack:
I tried to understand the cause, and it looks like on the conn.go file line 242, you assume the the msg has at least length of 32 bytes, but I added few print outs, and  the msg is empty in some cases (with len of 0)
Any idea how to fix this issue?

echo: http: panic serving [::1]:61067: runtime error: slice bounds out of range
goroutine 34 [running]:
net/http.(*conn).serve.func1(0xc0421920a0)
	C:/Go/src/net/http/server.go:1726 +0xd7
panic(0x881be0, 0xb9f680)
	C:/Go/src/runtime/panic.go:502 +0x237
github.com/Rhymen/go-whatsapp.(*Conn).decryptBinaryMessage(0xc04219a1c0, 0xbcba08, 0x0, 0x0, 0x0, 0x0, 0x800a)
	C:/workspaces/src/github.com/Rhymen/go-whatsapp/conn.go:242 +0x3d2
github.com/Rhymen/go-whatsapp.(*Conn).query(0xc04219a1c0, 0x90e2a3, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	C:/workspaces/src/github.com/Rhymen/go-whatsapp/contact.go:155 +0x40c
github.com/Rhymen/go-whatsapp.(*Conn).Contacts(0xc04219a1c0, 0x0, 0x0, 0xbcba08)
	C:/workspaces/src/github.com/Rhymen/go-whatsapp/contact.go:103 +0x7d
myproject/server/business/whats.(*waSession).GetContacts(0xc042055c18, 0x0, 0x0, 0x8e8bc0, 0x0, 0x0)
	C:/workspaces/src/myproject/server/business/whats/session.go:79 +0x83
myproject/server/rest.whatsAppContacts(0x970640, 0xc04219a150, 0xc04219a000, 0xc0421621e0)

**Comment by jhow2892** [comment] 2018-08-11 20:51
Hi, I try to download the latest version and reinstall it, I am able to normally extract the user name through Contact with the following command wac.Store.Contacts [message.Info.RemoteJid] .Notify

**Comment by Rhymen** [comment] 2018-08-11 20:59
I tried to debug it aswell, but I couldn't reproduce the error. As @jhow2892 mentioned, you can get the contact by looking into `wac.Store.Contacts[jid]`. The `wac.Contacts()` function is used to update the local store with the values from your phone. You don't need to do this when you start your program, because whatsapp syncs the contacts once after every login. 

What does the `wac.Contacts()` func respond for you? Watch out to not expose any phone numbers or names. As for me it responds with `{response map[type:contacts duplicate:true] <nil>}`.

**Comment by nuwaida** [comment] 2018-08-12 18:53
Hi,
Thanks guys for the quick response.
I'm looking to get all contacts, not only one by jid. 
When I call wac.Contacts() from last week the code, I used to get this result {response map[type:contacts duplicate:true] <nil>}, but since I update to the new code, that stores the contact is wac.Store and I call wac.Contacts() I get the above panic.
I tried your suggestion, and now I'm not calling wac.Contacts(), I do login, I get a session with no errors, few seconds later I print out the wac.Store.Contacts, and I get empty map. 
Here is my code: is there anything I'm doing wrong:

func (ws *waSession) GetContacts() (waContacts []WaContact, err error) {
	waContacts = make([]WaContact, 0)
	//_, err = ws.wac.Contacts()
	//if err != nil {
	//	return waContacts, fmt.Errorf("error loading contacts %s", err)
	//}

	contacts := ws.wac.Store.Contacts
	for key, contact := range contacts {
		fmt.Printf("contact (%s): %#v\n", key, contact)
		waContacts = append(waContacts, WaContact{
			Name: contact.Name,
			Phone: key,
			ShortName: contact.Short,
		})
	}
	return waContacts,nil
}

**Comment by SchulteMK** [comment] 2018-08-15 13:40
The stacktrace obove shows that the error got invoked in

> C:/workspaces/src/github.com/Rhymen/go-whatsapp/contact.go:103 +0x7d

This line contains the `wac.writeBinary(...)` call inside the `Presence(...)` function. I don´t know why it fails, but this function call does not correspond to your described error for calling `Contacts()`. Maybe comment out the call of `Presence(...)` for testing purposes.

**Comment by nuwaida** [comment] 2018-08-18 09:27
Hi,
As I said without calling contacts() I do not get anything. 
When I call contacts() I see the printouts from your package, and it panics few times (I have panic recovery) while printing the contacts, and before each panic I see this print out (with broadcast):  
 ```

**{user map[jid:status@broadcast] <nil>}**
echo: http: panic serving [::1]:51429: runtime error: slice bounds out of range
goroutine 712 [running]:
net/http.(*conn).serve.func1(0xc042207540)
	C:/Go/src/net/http/server.go:1726 +0xd7
panic(0x8f0240, 0xc5a950)
	C:/Go/src/runtime/panic.go:502 +0x237
github.com/Rhymen/go-whatsapp.(*Conn).decryptBinaryMessage(0xc0421de1c0, 0xc8ab78, 0x0, 0x0, 0x0, 0x0, 0x800a)
	C:/workspaces/src/github.com/Rhymen/go-whatsapp/conn.go:246 +0x3d2
github.com/Rhymen/go-whatsapp.(*Conn).query(0xc0421de1c0, 0x98a5fa, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	C:/workspaces/src/github.com/Rhymen/go-whatsapp/contact.go:155 +0x40c
github.com/Rhymen/go-whatsapp.(*Conn).Contacts(0xc0421de1c0, 0x0, 0x0, 0xc8ab78)
	C:/workspaces/src/github.com/Rhymen/go-whatsapp/contact.go:103 +0x7d
```

I was able to fix this issue when I added this code, I'm not sure this is the correct fix:

```
func (wac *Conn) decryptBinaryMessage(msg []byte) (*binary.Node, error) {
	//message validation
	if len(msg) == 0 {
		fmt.Println("Got empty msg to decrypt [%s]", msg)
		return nil, nil
	}
	h2 := hmac.New(sha256.New, wac.session.MacKey)
	h2.Write([]byte(msg[32:])) 
....
```

**Comment by Rhymen** [comment] 2019-02-03 14:09
Fixed in https://github.com/Rhymen/go-whatsapp/commit/955ab6fd07bd0d5ab5ef313ce3a3663f58b8bbe7

**Closed by Rhymen** 2019-02-03 14:09 UTC
